export const DEFAULT_CURRENT_TEMPERATURE_F = 70;
export const DEFAULT_HEAT_SETPOINT_F = 68;
export const DEFAULT_COOL_SETPOINT_F = 76;
export const DEFAULT_TARGET_TEMPERATURE_C = 20;

export const BRIGHTNESS_UPDATE_GUARD_MS = 150;
export const LIGHTBULB_ON_SET_DELAY_MS = 50;
